### ISSUE TITLE
count most common words in the entire README

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#137]

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#142](https://github.com/h1alexbel/sr-detection/issues/142), [#143](https://github.com/h1alexbel/sr-detection/issues/143) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#142](https://github.com/h1alexbel/sr-detection/issues/142) is still not solved; solved: [#143](https://github.com/h1alexbel/sr-detection/issues/143).
