### ISSUE TITLE
sentiment analysis on README top description

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#153]
Let's try to do a sentiment analysis on first sentences in README. Our hypothesis is that `SR` repos  should have mostly `positive` sentiments, while repositories intended to reused, should have `neutral`. Let's use this model as "base": https://huggingface.co/cardiffnlp/twitter-roberta-base-sentiment-latest

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#211](https://github.com/h1alexbel/sr-detection/issues/211) is still not solved.

**Comment by h1alexbel** [comment]
blocked by #209
