### ISSUE TITLE
generate datasets with recipes from provided `STEPS` env

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#207]
In our `justfile` we have a bunch of experimental recipes that generate various output from input repositories. Let's add ability to build the datasets with those recipes too, via `--experimental` flag.

**Comment by h1alexbel** [comment]
Let's try to do introduce new `ENV` in our Dockerfile: `STEPS`, that will contain all the steps it should execute. For instance:

```env
STEPS=collect,etc...
```

The only problem is to invoke all the steps as Just recipes without knowing args (steps require different types of args!)

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#234](https://github.com/h1alexbel/sr-detection/issues/234) is still not solved.

**Comment by h1alexbel** [comment]
@rultor release, tag is `0.0.20`
