### ISSUE TITLE
Workflow Simplicity Score

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#244]
Currently, we collect the following information in `workflows` step:

* `w_jobs`
* `w_steps`
* `w_oss`

Let's try to minimize these values into single `w` score, that means Workflow Simplicity Score

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#291](https://github.com/h1alexbel/sr-detection/issues/291) is still not solved.
