### ISSUE TITLE
sr-data skeleton

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#5]

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#7](https://github.com/h1alexbel/sr-detection/issues/7) is still not solved; solved: [#6](https://github.com/h1alexbel/sr-detection/issues/6).

**Comment by 0pdd** [comment]
@h1alexbel all 2 puzzles are solved here: [#6](https://github.com/h1alexbel/sr-detection/issues/6), [#7](https://github.com/h1alexbel/sr-detection/issues/7).
