### ISSUE TITLE
.rultor.yml:40-45: Create release script for whole...

### ISSUE THREAD

**Issue by 0pdd** [h1alexbel/sr-detection#7]
The puzzle `5-1c14f85c` from #5 has to be resolved: 

https://github.com/h1alexbel/sr-detection/blob/fcacd5bb68422d50117390ce0ed98045e913f27f/.rultor.yml#L40-L45

The puzzle was created by @h1alexbel on 04-Jul-24. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by h1alexbel** [comment]
Let's create two-step release pipeline. First, we release our collected repositories: we will create `collect.yml` GitHub workflow, and trigger it with `tag` input. It will execute `just collect`, do minimal filtering, (and maybe preprocessing), and push output files to the `collect-$tag` branch, and in releases with respective tag too. Then, we should prepare `Dockerfile` for training container. This container should be started by `rultor`, and during the build, we will train the model on data, pushed by `collected.yml`, right inside docker container.

**Comment by 0pdd** [comment]
The puzzle `5-1c14f85c` has disappeared from the source code, that's why I closed this issue.
