### ISSUE TITLE
collect `build` content from `pom.xml` or `gradle.build`

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#74]
check: https://github.com/h1alexbel/sr-detection/issues/69#issuecomment-2373633132

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#117](https://github.com/h1alexbel/sr-detection/issues/117), [#118](https://github.com/h1alexbel/sr-detection/issues/118) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#118](https://github.com/h1alexbel/sr-detection/issues/118) is still not solved; solved: [#117](https://github.com/h1alexbel/sr-detection/issues/117).

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#122](https://github.com/h1alexbel/sr-detection/issues/122) is still not solved; solved: [#117](https://github.com/h1alexbel/sr-detection/issues/117), [#118](https://github.com/h1alexbel/sr-detection/issues/118).
