### ISSUE TITLE
implement all steps in `sr-data` that were defined in the paper draft

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/sr-detection#9]
Let' implement all the tasks we have, one by one in the `sr-data` module. Some of them are available in the https://github.com/h1alexbel/srdataset

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#19](https://github.com/h1alexbel/sr-detection/issues/19) is still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#19](https://github.com/h1alexbel/sr-detection/issues/19), [#23](https://github.com/h1alexbel/sr-detection/issues/23), [#24](https://github.com/h1alexbel/sr-detection/issues/24) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#23](https://github.com/h1alexbel/sr-detection/issues/23), [#24](https://github.com/h1alexbel/sr-detection/issues/24) are still not solved; solved: [#19](https://github.com/h1alexbel/sr-detection/issues/19).

**Comment by 0pdd** [comment]
@h1alexbel the puzzle [#24](https://github.com/h1alexbel/sr-detection/issues/24) is still not solved; solved: [#19](https://github.com/h1alexbel/sr-detection/issues/19), [#23](https://github.com/h1alexbel/sr-detection/issues/23).

**Comment by 0pdd** [comment]
@h1alexbel all 3 puzzles are solved here: [#19](https://github.com/h1alexbel/sr-detection/issues/19), [#23](https://github.com/h1alexbel/sr-detection/issues/23), [#24](https://github.com/h1alexbel/sr-detection/issues/24).
